"""Write OSINT reports to disk — Markdown + JSON."""

import json
import os
import sys
from datetime import datetime, timezone
from typing import Generator


def _safe_filename(ip: str) -> str:
    return ip.replace(".", "_").replace(":", "_")


def write(
    ip: str,
    phase1: str,
    phase2: str,
    phase3: str,
    raw_data: dict,
    output_dir: str,
    provider: str,
    model: str,
) -> dict:
    """
    Write three files:
      {ip}_{ts}.md          — OSINT report (Phase 1 + 2)
      {ip}_{ts}_pentest.md  — Penetration testing guide (Phase 3)
      {ip}_{ts}_raw.json    — Raw collector data + all AI outputs
    Returns dict with file paths.
    """
    os.makedirs(output_dir, exist_ok=True)
    ts   = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    base = f"{_safe_filename(ip)}_{ts}"

    md_path      = os.path.join(output_dir, f"{base}.md")
    pentest_path = os.path.join(output_dir, f"{base}_pentest.md")
    js_path      = os.path.join(output_dir, f"{base}_raw.json")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(
            f"# Shodan Xploiter — OSINT Report\n"
            f"**Target IP**: `{ip}`\n"
            f"**Generated**: {datetime.now(timezone.utc).isoformat()}\n"
            f"**AI Provider**: {provider} / {model}\n"
            f"\n---\n\n{phase1}\n\n---\n\n{phase2}\n\n---\n"
            f"*Generated by Shodan Xploiter v1.0*\n"
        )

    with open(pentest_path, "w", encoding="utf-8") as f:
        f.write(
            f"# Shodan Xploiter — Penetration Testing Guide\n"
            f"**Target IP**: `{ip}`\n"
            f"**Generated**: {datetime.now(timezone.utc).isoformat()}\n"
            f"**AI Provider**: {provider} / {model}\n"
            f"\n> **LEGAL**: This guide requires explicit written authorization.\n"
            f"\n---\n\n{phase3}\n\n---\n"
            f"*Generated by Shodan Xploiter v1.0*\n"
        )

    with open(js_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "meta": {
                    "ip": ip,
                    "generated": datetime.now(timezone.utc).isoformat(),
                    "provider": provider,
                    "model": model,
                },
                "raw": raw_data,
                "phase1_report":  phase1,
                "phase2_report":  phase2,
                "phase3_pentest": phase3,
            },
            f, indent=2, default=str,
        )

    return {"markdown": md_path, "pentest": pentest_path, "json": js_path}


def write_streaming(
    ip: str,
    phase1: str,
    phase2: str,
    phase3_stream: Generator,
    raw_data: dict,
    output_dir: str,
    provider: str,
    model: str,
) -> dict:
    """
    Streaming variant for Phase 3.
    Writes each chunk to file and stdout in real time.
    Phase 1 and 2 are written normally (already complete at call time).
    Returns the same path dict as write(), plus 'phase3' with the full assembled text.
    """
    os.makedirs(output_dir, exist_ok=True)
    ts   = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    base = f"{_safe_filename(ip)}_{ts}"

    md_path      = os.path.join(output_dir, f"{base}.md")
    pentest_path = os.path.join(output_dir, f"{base}_pentest.md")
    js_path      = os.path.join(output_dir, f"{base}_raw.json")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(
            f"# Shodan Xploiter — OSINT Report\n"
            f"**Target IP**: `{ip}`\n"
            f"**Generated**: {datetime.now(timezone.utc).isoformat()}\n"
            f"**AI Provider**: {provider} / {model}\n"
            f"\n---\n\n{phase1}\n\n---\n\n{phase2}\n\n---\n"
            f"*Generated by Shodan Xploiter v1.0*\n"
        )

    chunks = []
    with open(pentest_path, "w", encoding="utf-8") as f:
        f.write(
            f"# Shodan Xploiter — Penetration Testing Guide\n"
            f"**Target IP**: `{ip}`\n"
            f"**Generated**: {datetime.now(timezone.utc).isoformat()}\n"
            f"**AI Provider**: {provider} / {model}\n"
            f"\n> **LEGAL**: This guide requires explicit written authorization.\n"
            f"\n---\n\n"
        )
        for chunk in phase3_stream:
            f.write(chunk)
            f.flush()
            sys.stdout.write(chunk)
            sys.stdout.flush()
            chunks.append(chunk)
        f.write("\n---\n*Generated by Shodan Xploiter v1.0*\n")

    sys.stdout.write("\n")
    sys.stdout.flush()

    phase3_full = "".join(chunks)

    with open(js_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "meta": {
                    "ip": ip,
                    "generated": datetime.now(timezone.utc).isoformat(),
                    "provider": provider,
                    "model": model,
                },
                "raw": raw_data,
                "phase1_report":  phase1,
                "phase2_report":  phase2,
                "phase3_pentest": phase3_full,
            },
            f, indent=2, default=str,
        )

    return {
        "markdown": md_path,
        "pentest":  pentest_path,
        "json":     js_path,
        "phase3":   phase3_full,
    }
